### ISSUE TITLE
Can't generate doc

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#224]
## Brief summary of issue

I'm experiencing trouble when trying to add documentation. Namely,
```
make doc
```
generates the following output:
```
Generating doxygen
make: *** [doc] Error 1
```

Removing the appropriate `>/dev/null` from the Makefile, I get:
```
Generating doxygen
error: configuration file ./doc/cmsgemos.cfg not found!
```

Indeed the file doesn't exist. Am I doing something wrong?
### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

`make doc` works

## Current Behavior

See above

## Possible Solution (for bugs)

Include the missing file

## Context

Willing to document changes in PR #222

**Comment by lmoureaux** [comment]
@jsturdy (only admins can assign)

**Comment by jsturdy** [comment]
I'm pretty sure (read, certain) that `doc` target is not validated.
In my local area, I had put the configs in `docs/`, but have not yet pushed the config.
I will can run through and make sure things build with the given config and add a patch that you can `rebase` off.

**Comment by jsturdy** [comment]
You should be able to `fetch` and `rebase` from `cms-gem-daq-project:feature/gemonlinedb` to fix this in your working tree.  If any issues remain reopen this.

**Comment by lmoureaux** [comment]
```
error: tag OUTPUT_DIRECTORY: Output directory `/afs/cern.ch/user/l/lmoureau/GEM/gemonlinedb/cmsgemos/docs/build/' does not exist and cannot be created
```
Works if I create the directory by hand. Only maintainers can reopen issues in this repo.

**Comment by jsturdy** [comment]
OK, `build` doesn't have anything persistent in it, so #227 should fix that.
There *shouldn't* be anything else preventing the doc building, but doc building is really my least concern at present...

**Comment by lpetre-ulb** [comment]
The documentation generation is still failing with the update build system. On the first attempt, one gets the following error:
```bash
$ scl enable devtoolset-8 -- make doc
[...]
Generating doxygen
Warning: Tag `SYMBOL_CACHE_SIZE' at line 304 of file ./doc/cmsgemos.cfg has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `SHOW_DIRECTORIES' at line 498 of file ./doc/cmsgemos.cfg has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `HTML_ALIGN_MEMBERS' at line 848 of file ./doc/cmsgemos.cfg has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `USE_INLINE_TREES' at line 1001 of file ./doc/cmsgemos.cfg has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
error: tag OUTPUT_DIRECTORY: Output directory `//doc/build/' does not exist and cannot be created
Exiting...
make: *** [doc] Error 1
```

While on the second attempt, this error is thrown:
``` bash
$ scl enable devtoolset-8 -- make doc
[...]
Generating doxygen
mkdir: cannot create directory ‘./doc/build’: File exists
make: *** [doc] Error 1
```

**Comment by jsturdy** [comment]
> The documentation generation is still failing with the update build system.

To be clear, there is no "updated build system" in this repository.

That being said, I have updated the legacy branch to build the docs successfully (and in a coherent way across all repos, so they all got updated as minimally as I could), so those changes *could* be `cherry-picked` (probably) into this (where "this" I understand from @lpetre-ulb's comment to be the non-legacy codebase), but I really fail to see the point in doing that, considering all the massive restructuring that is foreseen...

In any event, for legacy code, PRs are forthcoming following some final cleanup

**Comment by lpetre-ulb** [comment]
> > The documentation generation is still failing with the update build system.
> 
> To be clear, there is no "updated build system" in this repository.

Okay, I thought that #311 updated the build system. Sorry about that.

> That being said, I have updated the legacy branch to build the docs successfully (and in a coherent way across all repos, so they all got updated as minimally as I could), so those changes _could_ be `cherry-picked` (probably) into this (where "this" I understand from @lpetre-ulb's comment to be the non-legacy codebase), but I really fail to see the point in doing that, considering all the massive restructuring that is foreseen...

Indeed, when I posted this that reply, we were still discussing the migration. This issue is no longer relevant for the `develop` branch.

> In any event, for legacy code, PRs are forthcoming following some final cleanup

:+1:
